apiVersion: v1
kind: Service
metadata:
  name: stellarcd-admin-api
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: admin-api
  selector:
    control-plane: controller-manager
